name: Sync to AWS Repo

on:
  push:

jobs:
  sync:
    if: github.actor != 'sync-bot'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout DevOps Repo
        uses: actions/checkout@v3

      - name: Sync to AWS Repo
        run: |
          git config --global user.name "sync-bot"
          git config --global user.email "sync@github.com"

          git clone https://x-access-token:${{ secrets.SYNC_TOKEN }}@github.com/Soumyajit-Paramanick/KodeKloud-Engineer-AWS-tasks.git aws-repo

          rsync -av --exclude='.git' --exclude='.github' ./ aws-repo/

          cd aws-repo
          git add .
          git commit -m "Auto sync from DevOps repo" || echo "No changes"
          git push